name: Release Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

        # Add Bun dependency caching
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies (Bun)
        run: bun install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew Executable
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Get version from app.json
        id: version
        run: |
          VERSION=$(node -p "require('./app.json').expo.version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PLapp-${{ steps.version.outputs.version }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Download APK for Release
        run: |
          cp android/app/build/outputs/apk/release/app-release.apk ./PLapp.apk
          echo "APK copied as PLapp.apk"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            ## What's New

            Android APK release for version ${{ steps.version.outputs.version }}

            ### Download
            Download the APK file below and install it on your Android device.

            ### Installation
            1. Download the APK file
            2. Enable "Install from Unknown Sources" in your Android settings
            3. Open the downloaded APK file
            4. Follow the installation prompts

            ### Features
            - Profit and Loss Calculator for Stocks
            - Persistent storage with Zustand
            - Indian currency formatting
            - Collapsible statement cards
            - Earnings calculation with charges
            - Modern UI with animations

            ### Build Info
            - Built with React Native & Expo
            - Package Manager: Bun
            - Node.js Version: ${{ env.NODE_VERSION }}
          files: PLapp.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 Android APK build completed successfully!
              
              **Version:** ${{ steps.version.outputs.version }}
              
              Download the APK from the [latest release](https://github.com/${{ github.repository }}/releases/latest).`
            })
